"use client";

import { useEffect, useState } from "react";
import { useStore } from "@/store/useStore";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Lightbulb } from "lucide-react";

interface InsightsResponse {
  insights: string;
}

export const InsightsPanel = () => {
  const { results, processes, algorithm, timeQuantum, mlqConfig, totalDuration } = useStore();

  const [insights, setInsights] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!results || processes.length === 0 || results.metrics.length === 0) {
      setInsights(null);
      setError(null);
      return;
    }

    const controller = new AbortController();

    const fetchInsights = async () => {
      setLoading(true);
      setError(null);

      try {
        const res = await fetch("/api/insights", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            algorithm,
            timeQuantum,
            mlqConfig,
            processes,
            results,
          }),
          signal: controller.signal,
        });

        if (!res.ok) {
          throw new Error(`Request failed with status ${res.status}`);
        }

        const data: InsightsResponse = await res.json();
        setInsights(data.insights);
      } catch {
        if (!controller.signal.aborted) {
          setError("Could not load AI insights. Try again after a moment.");
        }
      } finally {
        if (!controller.signal.aborted) {
          setLoading(false);
        }
      }
    };

    fetchInsights();

    return () => controller.abort();
  }, [algorithm, timeQuantum, mlqConfig, processes, results]);

  if (!results) return null;

  const renderInsights = () => {
    if (loading) {
      return (
        <p className="text-xs text-slate-500 dark:text-slate-400">
          Asking the LLM for an explanation of this schedule…
        </p>
      );
    }

    if (error) {
      return (
        <p className="text-xs text-red-500 dark:text-red-400">
          {error}
        </p>
      );
    }

    if (!insights) {
      return (
        <p className="text-xs text-slate-500 dark:text-slate-400">
          No AI insights yet. Run a simulation to generate a schedule first.
        </p>
      );
    }

    return insights.split("\n").map((line, idx) =>
      line.trim().length === 0 ? null : (
        <p key={idx} className="text-sm text-slate-700 dark:text-slate-200 leading-relaxed">
          {line}
        </p>
      )
    );
  };

  return (
    <Card className="glass-card shadow-lg border-slate-200/60 dark:border-slate-700/60 card-hover transition-all duration-300 rounded-2xl overflow-hidden">
      <CardHeader className="pb-3 flex flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Lightbulb className="w-5 h-5 text-amber-500 dark:text-amber-300" />
          <div>
            <CardTitle className="text-slate-800 dark:text-slate-100 text-base">
              AI Performance Insights
            </CardTitle>
            <p className="text-[11px] text-slate-500 dark:text-slate-400">
              Generated by a language model based on the current schedule.
            </p>
          </div>
        </div>
        <Badge
          variant="outline"
          className="text-[11px] font-mono uppercase tracking-wider border-amber-300/60 dark:border-amber-500/60 text-amber-700 dark:text-amber-200 bg-amber-50/70 dark:bg-amber-950/40"
        >
          t = {totalDuration.toFixed ? totalDuration.toFixed(1) : totalDuration}s
        </Badge>
      </CardHeader>
      <CardContent className="space-y-3">
        {renderInsights()}
      </CardContent>
    </Card>
  );
};
